// <auto-generated />
using MVC_Library.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MVC_Library.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    partial class LibraryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MVC_Library.Models.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PageCount")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Fyodor Dostoyevski",
                            PageCount = 687,
                            Title = "Suç ve Ceza"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Victor Hugo",
                            PageCount = 1232,
                            Title = "Sefiller"
                        },
                        new
                        {
                            Id = 3,
                            Author = "George Orwell",
                            PageCount = 328,
                            Title = "1984"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Sabahattin Ali",
                            PageCount = 160,
                            Title = "Kürk Mantolu Madonna"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Oğuz Atay",
                            PageCount = 724,
                            Title = "Tutunamayanlar"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Paulo Coelho",
                            PageCount = 184,
                            Title = "Simyacı"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Franz Kafka",
                            PageCount = 104,
                            Title = "Dönüşüm"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Jack London",
                            PageCount = 256,
                            Title = "Beyaz Diş"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
